-- Migración 033: Limpieza completa + importación datos verificados Excel
-- Solo para la base de datos de producción (refugios / polished-shadow)
-- Cabin mapping producción: azul=1, rojo=7, verde=3, negro/Casa=4

-- 1. ELIMINAR DATOS SINTÉTICOS / DEMO / PDF
DELETE FROM reservations WHERE notes LIKE 'ASSET_PDF_RESERVAS_2025%';
DELETE FROM reservations WHERE notes LIKE 'ASSET_PDF_RESERVAS_2026%';
DELETE FROM reservations WHERE notes = 'MANUAL_FEB_2026_FINAL';
DELETE FROM reservations WHERE notes = 'Importado staging PDF RESERVAS 2026';
DELETE FROM reservations WHERE notes LIKE 'ASSET_PDF_VENTAS_2026%';
DELETE FROM reservations WHERE notes = 'Reserva demo';
DELETE FROM reservations WHERE notes = 'ASSET_CORRECTED_2026';
DELETE FROM reservations WHERE notes = 'ASSET_CORRECTED_2025_2026';

-- 2. ELIMINAR GUEST DEMO
DELETE FROM guests WHERE LOWER(full_name) = 'cliente demo';

-- 3. INSERTAR GUESTS FALTANTES EN PRODUCCIÓN
INSERT INTO guests (full_name, notes) SELECT 'Alejandra Stay', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Alejandra Stay'));
INSERT INTO guests (full_name, notes) SELECT 'Andorra Casa', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Andorra Casa'));
INSERT INTO guests (full_name, notes) SELECT 'Andrea Romeny', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Andrea Romeny'));
INSERT INTO guests (full_name, notes) SELECT 'Andres Vasquez', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Andres Vasquez'));
INSERT INTO guests (full_name, notes) SELECT 'Atigilio', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Atigilio'));
INSERT INTO guests (full_name, notes) SELECT 'Begoña Asfura', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Begoña Asfura'));
INSERT INTO guests (full_name, notes) SELECT 'Bibiana Rubini', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Bibiana Rubini'));
INSERT INTO guests (full_name, notes) SELECT 'Bosnia Refugio 1', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Bosnia Refugio 1'));
INSERT INTO guests (full_name, notes) SELECT 'Carlos Delgado', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Carlos Delgado'));
INSERT INTO guests (full_name, notes) SELECT 'Carolina Andrea Peña', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Carolina Andrea Peña'));
INSERT INTO guests (full_name, notes) SELECT 'Carolina Bustos', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Carolina Bustos'));
INSERT INTO guests (full_name, notes) SELECT 'Carolina Diaz Yaeger', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Carolina Diaz Yaeger'));
INSERT INTO guests (full_name, notes) SELECT 'Carolina Senn', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Carolina Senn'));
INSERT INTO guests (full_name, notes) SELECT 'Catalina Riveros', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Catalina Riveros'));
INSERT INTO guests (full_name, notes) SELECT 'Cesar Soto', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Cesar Soto'));
INSERT INTO guests (full_name, notes) SELECT 'Christian Gardiol', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Christian Gardiol'));
INSERT INTO guests (full_name, notes) SELECT 'Daniel Mclaughlin', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Daniel Mclaughlin'));
INSERT INTO guests (full_name, notes) SELECT 'Daniela Gonzales', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Daniela Gonzales'));
INSERT INTO guests (full_name, notes) SELECT 'Daniela Herrera', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Daniela Herrera'));
INSERT INTO guests (full_name, notes) SELECT 'Debora Castillo', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Debora Castillo'));
INSERT INTO guests (full_name, notes) SELECT 'Diego Cid', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Diego Cid'));
INSERT INTO guests (full_name, notes) SELECT 'Esteban Contreras', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Esteban Contreras'));
INSERT INTO guests (full_name, notes) SELECT 'Eva Piccars', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Eva Piccars'));
INSERT INTO guests (full_name, notes) SELECT 'Exequeil', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Exequeil'));
INSERT INTO guests (full_name, notes) SELECT 'Felipe Castaña', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Felipe Castaña'));
INSERT INTO guests (full_name, notes) SELECT 'Felipe Garin', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Felipe Garin'));
INSERT INTO guests (full_name, notes) SELECT 'Felipe Villa Vicencio', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Felipe Villa Vicencio'));
INSERT INTO guests (full_name, notes) SELECT 'Filipe Hernandez', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Filipe Hernandez'));
INSERT INTO guests (full_name, notes) SELECT 'Gabriela Verdugo', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Gabriela Verdugo'));
INSERT INTO guests (full_name, notes) SELECT 'Gaspar Aunfraric', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Gaspar Aunfraric'));
INSERT INTO guests (full_name, notes) SELECT 'Gustavo Canales', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Gustavo Canales'));
INSERT INTO guests (full_name, notes) SELECT 'Hernan Wunderlich', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Hernan Wunderlich'));
INSERT INTO guests (full_name, notes) SELECT 'Ignacio Mellado', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Ignacio Mellado'));
INSERT INTO guests (full_name, notes) SELECT 'Ingrid Mellado', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Ingrid Mellado'));
INSERT INTO guests (full_name, notes) SELECT 'JAVIER', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('JAVIER'));
INSERT INTO guests (full_name, notes) SELECT 'Javier Diaz', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Javier Diaz'));
INSERT INTO guests (full_name, notes) SELECT 'Javier Lescano', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Javier Lescano'));
INSERT INTO guests (full_name, notes) SELECT 'Javier Perez', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Javier Perez'));
INSERT INTO guests (full_name, notes) SELECT 'Javier y Camila', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Javier y Camila'));
INSERT INTO guests (full_name, notes) SELECT 'Javiera Pefaur', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Javiera Pefaur'));
INSERT INTO guests (full_name, notes) SELECT 'Jorge Lichtscheidi', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Jorge Lichtscheidi'));
INSERT INTO guests (full_name, notes) SELECT 'Jorge Perez', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Jorge Perez'));
INSERT INTO guests (full_name, notes) SELECT 'JUAN', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('JUAN'));
INSERT INTO guests (full_name, notes) SELECT 'Julia Quinteros (Julio en reservas)', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Julia Quinteros (Julio en reservas)'));
INSERT INTO guests (full_name, notes) SELECT 'Leonel Muñoz', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Leonel Muñoz'));
INSERT INTO guests (full_name, notes) SELECT 'Loreto Hofer', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Loreto Hofer'));
INSERT INTO guests (full_name, notes) SELECT 'Lourdes Velasques', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Lourdes Velasques'));
INSERT INTO guests (full_name, notes) SELECT 'Lourdes Velasquez', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Lourdes Velasquez'));
INSERT INTO guests (full_name, notes) SELECT 'Marcela Perez', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Marcela Perez'));
INSERT INTO guests (full_name, notes) SELECT 'Marcio Zanetti', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Marcio Zanetti'));
INSERT INTO guests (full_name, notes) SELECT 'MARIA', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('MARIA'));
INSERT INTO guests (full_name, notes) SELECT 'Maria Constanza Moraga', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Maria Constanza Moraga'));
INSERT INTO guests (full_name, notes) SELECT 'Maria Victoria Gozalves', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Maria Victoria Gozalves'));
INSERT INTO guests (full_name, notes) SELECT 'Mariela Offmann', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Mariela Offmann'));
INSERT INTO guests (full_name, notes) SELECT 'Marta Martu', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Marta Martu'));
INSERT INTO guests (full_name, notes) SELECT 'Martin Basilio', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Martin Basilio'));
INSERT INTO guests (full_name, notes) SELECT 'Matias Lomboy', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Matias Lomboy'));
INSERT INTO guests (full_name, notes) SELECT 'Michel Angelo Lapadula', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Michel Angelo Lapadula'));
INSERT INTO guests (full_name, notes) SELECT 'Oscar Contreras', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Oscar Contreras'));
INSERT INTO guests (full_name, notes) SELECT 'Pablo Rodriguez Carrasco', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Pablo Rodriguez Carrasco'));
INSERT INTO guests (full_name, notes) SELECT 'Pamela Espinoza', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Pamela Espinoza'));
INSERT INTO guests (full_name, notes) SELECT 'Pamela Vera', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Pamela Vera'));
INSERT INTO guests (full_name, notes) SELECT 'Paola Romero', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Paola Romero'));
INSERT INTO guests (full_name, notes) SELECT 'Patricia Bustamante', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Patricia Bustamante'));
INSERT INTO guests (full_name, notes) SELECT 'Paulina Vergara', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Paulina Vergara'));
INSERT INTO guests (full_name, notes) SELECT 'Paulo Unzueta', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Paulo Unzueta'));
INSERT INTO guests (full_name, notes) SELECT 'Rainer Muehlberger', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Rainer Muehlberger'));
INSERT INTO guests (full_name, notes) SELECT 'Rene Tapia', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Rene Tapia'));
INSERT INTO guests (full_name, notes) SELECT 'Roberto Necochea', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Roberto Necochea'));
INSERT INTO guests (full_name, notes) SELECT 'Rodrigo Ibañez', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Rodrigo Ibañez'));
INSERT INTO guests (full_name, notes) SELECT 'Rodrigo Salinas', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Rodrigo Salinas'));
INSERT INTO guests (full_name, notes) SELECT 'Romina Sanhueza', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Romina Sanhueza'));
INSERT INTO guests (full_name, notes) SELECT 'Sebastian Gianfagma', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Sebastian Gianfagma'));
INSERT INTO guests (full_name, notes) SELECT 'Susana Montesino', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Susana Montesino'));
INSERT INTO guests (full_name, notes) SELECT 'Thomas Hoel', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Thomas Hoel'));
INSERT INTO guests (full_name, notes) SELECT 'Vanina Martinez', 'ASSET_CORRECTED_IMPORT' WHERE NOT EXISTS (SELECT 1 FROM guests WHERE LOWER(full_name) = LOWER('Vanina Martinez'));

-- 4. INSERTAR RESERVAS 2026 VERIFICADAS (Excel)
INSERT INTO reservations (guest_id,cabin_id,check_in,check_out,guests_count,total_amount,source,payment_method,status,lead_stage,notes) VALUES
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('camila muñoz') ORDER BY id ASC LIMIT 1),4,'2026-01-01','2026-01-03',7,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Camila Muñoz, Casa AvA
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('fernanda escorza') ORDER BY id ASC LIMIT 1),7,'2026-01-14','2026-01-17',2,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Fernanda Escorza
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('barbara') ORDER BY id ASC LIMIT 1),7,'2026-01-17','2026-01-18',2,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Barbara
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('nicolas muñoz') ORDER BY id ASC LIMIT 1),7,'2026-01-20','2026-01-22',2,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Nicolas Muñoz
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('francisco espinoza') ORDER BY id ASC LIMIT 1),3,'2026-01-22','2026-01-26',2,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Francisco Espinoza
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('juan carlos') ORDER BY id ASC LIMIT 1),7,'2026-01-23','2026-01-25',2,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Juan Carlos
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('alberto etchegaray') ORDER BY id ASC LIMIT 1),4,'2026-01-30','2026-02-02',5,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Alberto Etchegaray, Casa AvA
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('paulina cabezas') ORDER BY id ASC LIMIT 1),1,'2026-02-04','2026-02-06',2,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Paulina Cabezas
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('rodrigo espinoza') ORDER BY id ASC LIMIT 1),7,'2026-02-05','2026-02-10',2,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Rodrigo Espinoza
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('marcela rodrigues') ORDER BY id ASC LIMIT 1),3,'2026-02-05','2026-02-07',2,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Marcela Rodrigues
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('felipe garin') ORDER BY id ASC LIMIT 1),4,'2026-02-06','2026-02-09',4,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Felipe Garin, Casa AvA
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('gabriela soto') ORDER BY id ASC LIMIT 1),1,'2026-02-06','2026-02-08',2,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Gabriela Soto
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('nicolas sanchez') ORDER BY id ASC LIMIT 1),3,'2026-02-08','2026-02-12',3,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Nicolas Sanchez
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('russel king') ORDER BY id ASC LIMIT 1),4,'2026-02-09','2026-02-12',4,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Russel King, Casa AvA
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('alejandra maturana') ORDER BY id ASC LIMIT 1),1,'2026-02-09','2026-02-12',2,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Alejandra Maturana
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('cristobal muhr') ORDER BY id ASC LIMIT 1),7,'2026-02-10','2026-02-13',3,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Cristobal Muhr
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('valentina riquelme') ORDER BY id ASC LIMIT 1),3,'2026-02-13','2026-02-15',2,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Valentina Riquelme
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('ariana sepulveda') ORDER BY id ASC LIMIT 1),1,'2026-02-13','2026-02-19',2,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Ariana Sepulveda
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('andres goycolea') ORDER BY id ASC LIMIT 1),4,'2026-02-14','2026-02-19',5,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Andres Goycolea, Casa AvA
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('javiera garrido') ORDER BY id ASC LIMIT 1),7,'2026-02-15','2026-02-18',3,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Javiera Garrido
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('juan vidria') ORDER BY id ASC LIMIT 1),3,'2026-02-16','2026-02-18',2,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Juan Vidria
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('luis reyes') ORDER BY id ASC LIMIT 1),7,'2026-02-18','2026-02-21',2,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Luis Reyes
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('eva piccars') ORDER BY id ASC LIMIT 1),3,'2026-02-19','2026-02-24',3,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Eva Piccars
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('natalia ureta') ORDER BY id ASC LIMIT 1),1,'2026-02-19','2026-02-22',4,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Natalia Ureta
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('camila muñoz') ORDER BY id ASC LIMIT 1),7,'2026-02-21','2026-02-27',2,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Camila Muñoz
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('lourdes velez') ORDER BY id ASC LIMIT 1),1,'2026-02-27','2026-03-03',2,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Lourdes Velez (→ Marzo)
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('joao viana') ORDER BY id ASC LIMIT 1),4,'2026-08-26','2026-08-29',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Joao Viana, Casa AvA
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('joao viana') ORDER BY id ASC LIMIT 1),1,'2026-08-26','2026-08-29',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Joao Viana, C1
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('joao viana') ORDER BY id ASC LIMIT 1),7,'2026-08-26','2026-08-29',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Joao Viana, C2
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('javier') ORDER BY id ASC LIMIT 1),4,'2026-08-31','2026-09-01',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Javier, Casa AvA
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('sebastian perez') ORDER BY id ASC LIMIT 1),3,'2026-08-31','2026-09-05',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Sebastian Perez
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('martin basilio') ORDER BY id ASC LIMIT 1),7,'2026-08-31','2026-09-03',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Martin Basilio
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('gaspar aunfraric') ORDER BY id ASC LIMIT 1),1,'2026-08-31','2026-09-05',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Gaspar Aunfraric
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('maria') ORDER BY id ASC LIMIT 1),4,'2026-08-31','2026-09-04',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Maria, Casa AvA
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('tomas') ORDER BY id ASC LIMIT 1),7,'2026-09-04','2026-09-06',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Tomas
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('exequeil') ORDER BY id ASC LIMIT 1),3,'2026-09-05','2026-09-06',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Exequeil
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('oscar') ORDER BY id ASC LIMIT 1),7,'2026-09-06','2026-09-07',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Oscar
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('juan') ORDER BY id ASC LIMIT 1),4,'2026-09-07','2026-09-08',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Juan, Casa AvA
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('andraz') ORDER BY id ASC LIMIT 1),1,'2026-09-08','2026-09-29',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Andraz
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('rodrigo salinas') ORDER BY id ASC LIMIT 1),7,'2026-09-10','2026-09-13',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Rodrigo Salinas
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('leonel muñoz') ORDER BY id ASC LIMIT 1),4,'2026-09-12','2026-09-16',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Leonel Muñoz, Casa AvA
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('ximena moraga') ORDER BY id ASC LIMIT 1),3,'2026-09-12','2026-09-17',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Ximena Moraga
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('bibiana rubini') ORDER BY id ASC LIMIT 1),7,'2026-09-13','2026-09-17',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Bibiana Rubini
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('lourdes velez') ORDER BY id ASC LIMIT 1),4,'2026-09-16','2026-09-21',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Lourdes Velez, Casa AvA
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('jaime') ORDER BY id ASC LIMIT 1),3,'2026-09-17','2026-09-19',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Jaime
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('rene valdenegro') ORDER BY id ASC LIMIT 1),7,'2026-09-17','2026-09-19',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Rene Valdenegro
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('marta martu') ORDER BY id ASC LIMIT 1),3,'2026-09-19','2026-09-23',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Marta Martu
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('ignacio mellado') ORDER BY id ASC LIMIT 1),7,'2026-09-19','2026-09-29',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Ignacio Mellado
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('bosnia refugio 1') ORDER BY id ASC LIMIT 1),3,'2026-09-25','2026-09-29',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Bosnia Refugio 1
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('andorra casa') ORDER BY id ASC LIMIT 1),4,'2026-09-26','2026-09-29',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Andorra Casa, Casa AvA
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('andraz') ORDER BY id ASC LIMIT 1),1,'2026-10-01','2026-10-12',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Andraz
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('andorra casa') ORDER BY id ASC LIMIT 1),4,'2026-10-01','2026-10-15',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Andorra Casa, Casa AvA
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('bosnia refugio 1') ORDER BY id ASC LIMIT 1),7,'2026-10-01','2026-10-15',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Bosnia, C2
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('bosnia refugio 1') ORDER BY id ASC LIMIT 1),3,'2026-10-01','2026-10-15',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Bosnia, C3
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('agustin') ORDER BY id ASC LIMIT 1),4,'2026-10-15','2026-10-20',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Agustin, Casa AvA
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('valentina riquelme') ORDER BY id ASC LIMIT 1),4,'2026-10-27','2026-10-31',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'), -- Valentina, Casa AvA
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('camila muñoz') ORDER BY id ASC LIMIT 1),4,'2026-12-26','2026-12-30',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2026'); -- Camila Muñoz, Casa AvA

-- 5. INSERTAR RESERVAS 2025 VERIFICADAS (Excel)
INSERT INTO reservations (guest_id,cabin_id,check_in,check_out,guests_count,total_amount,source,payment_method,status,lead_stage,notes) VALUES
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('maria olivia') ORDER BY id ASC LIMIT 1),3,'2025-01-01','2025-01-02',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- Maria Olivia
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('andrea romeny') ORDER BY id ASC LIMIT 1),4,'2025-01-01','2025-01-02',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- Andrea
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('jorge perez') ORDER BY id ASC LIMIT 1),7,'2025-01-06','2025-01-12',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- Jorge
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('daniel mclaughlin') ORDER BY id ASC LIMIT 1),4,'2025-01-07','2025-01-11',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- Daniel
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('rainer muehlberger') ORDER BY id ASC LIMIT 1),1,'2025-01-08','2025-01-11',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- Rainer
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('javiera pefaur') ORDER BY id ASC LIMIT 1),3,'2025-01-10','2025-01-14',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- Javiera
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('fernando larumbe') ORDER BY id ASC LIMIT 1),1,'2025-01-22','2025-01-23',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- Fernando
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('martin echeverría') ORDER BY id ASC LIMIT 1),7,'2025-01-23','2025-01-27',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- Martin
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('loreto hofer') ORDER BY id ASC LIMIT 1),1,'2025-01-26','2025-01-28',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- loreto
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('yves romero') ORDER BY id ASC LIMIT 1),4,'2025-01-26','2025-02-01',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- ives
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('margarita steff') ORDER BY id ASC LIMIT 1),3,'2025-01-29','2025-02-04',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- margarita
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('kara bermejo') ORDER BY id ASC LIMIT 1),7,'2025-01-31','2025-02-02',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- kara
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('filipe hernandez') ORDER BY id ASC LIMIT 1),4,'2025-02-01','2025-02-04',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- Felipe
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('paola romero') ORDER BY id ASC LIMIT 1),1,'2025-02-04','2025-02-08',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- Paola
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('marita') ORDER BY id ASC LIMIT 1),4,'2025-02-04','2025-02-06',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- Marita
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('roberto necochea') ORDER BY id ASC LIMIT 1),3,'2025-02-04','2025-02-07',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- Roberto
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('susana montesino') ORDER BY id ASC LIMIT 1),7,'2025-02-04','2025-02-06',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- susana
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('julia quinteros (julio en reservas)') ORDER BY id ASC LIMIT 1),7,'2025-02-06','2025-02-12',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- julio
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('patricia bustamante') ORDER BY id ASC LIMIT 1),3,'2025-02-07','2025-02-09',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- patricia
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('pedro') ORDER BY id ASC LIMIT 1),1,'2025-02-08','2025-02-09',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- pedro
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('alejandra stay') ORDER BY id ASC LIMIT 1),4,'2025-02-08','2025-02-14',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- alejandra
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('daniel mora') ORDER BY id ASC LIMIT 1),7,'2025-02-12','2025-02-15',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- daniel
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('javier maldonado') ORDER BY id ASC LIMIT 1),3,'2025-02-13','2025-02-16',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- javier
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('bastian perei') ORDER BY id ASC LIMIT 1),1,'2025-02-15','2025-02-17',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- bastian
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('daniela gonzales') ORDER BY id ASC LIMIT 1),4,'2025-02-15','2025-02-18',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- daniela
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('natalia gonzáles') ORDER BY id ASC LIMIT 1),7,'2025-02-16','2025-02-19',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- natalia
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('nicole abarca') ORDER BY id ASC LIMIT 1),3,'2025-02-17','2025-02-22',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- nicole
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('enrique araos') ORDER BY id ASC LIMIT 1),1,'2025-02-17','2025-02-20',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- enrique
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('mariela offmann') ORDER BY id ASC LIMIT 1),4,'2025-02-20','2025-02-23',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- mariela
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('bruno cres') ORDER BY id ASC LIMIT 1),7,'2025-02-20','2025-02-23',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- bruno
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('javiera garrido') ORDER BY id ASC LIMIT 1),1,'2025-02-20','2025-02-23',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- javiera
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('esteban contreras') ORDER BY id ASC LIMIT 1),7,'2025-02-25','2025-02-28',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- esteban
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('daniel mora') ORDER BY id ASC LIMIT 1),1,'2025-02-27','2025-03-01',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- daniel
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('pablo morande') ORDER BY id ASC LIMIT 1),3,'2025-02-28','2025-03-02',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- pablo
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('andres larrain') ORDER BY id ASC LIMIT 1),4,'2025-03-07','2025-03-08',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- andres
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('felipe prado') ORDER BY id ASC LIMIT 1),7,'2025-03-07','2025-03-09',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- felipe
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('jorge lichtscheidi') ORDER BY id ASC LIMIT 1),1,'2025-03-08','2025-03-15',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- jorge
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('christian gardiol') ORDER BY id ASC LIMIT 1),3,'2025-03-18','2025-03-22',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- cristian
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('carolina bustos') ORDER BY id ASC LIMIT 1),7,'2025-03-19','2025-03-21',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- carolina
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('claire wood') ORDER BY id ASC LIMIT 1),4,'2025-04-18','2025-04-20',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- Claire
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('cesar soto') ORDER BY id ASC LIMIT 1),7,'2025-04-18','2025-04-20',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- cesar
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('rodrigo fernandez') ORDER BY id ASC LIMIT 1),1,'2025-04-18','2025-04-20',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- rodrigo
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('lucas gonzales') ORDER BY id ASC LIMIT 1),3,'2025-04-17','2025-04-20',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- lucas
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('sebastian perez') ORDER BY id ASC LIMIT 1),4,'2025-04-29','2025-05-04',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- sebastian
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('pamela espinoza') ORDER BY id ASC LIMIT 1),3,'2025-04-30','2025-05-03',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- pamela
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('javier y camila') ORDER BY id ASC LIMIT 1),3,'2025-04-01','2025-04-05',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- javier
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('rodrigo ibañez') ORDER BY id ASC LIMIT 1),3,'2025-05-03','2025-05-04',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- rodrigo
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('marcela perez') ORDER BY id ASC LIMIT 1),7,'2025-05-01','2025-05-04',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- marcela
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('carolina alvarez') ORDER BY id ASC LIMIT 1),1,'2025-05-02','2025-05-04',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- carolina
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('paulina vergara') ORDER BY id ASC LIMIT 1),4,'2025-05-16','2025-05-18',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- paulina
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('vanina martinez') ORDER BY id ASC LIMIT 1),4,'2025-05-18','2025-05-20',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- vanina
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('lourdes velasquez') ORDER BY id ASC LIMIT 1),4,'2025-06-06','2025-06-10',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- lourdes
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('maria francisca valenzuela') ORDER BY id ASC LIMIT 1),1,'2025-06-06','2025-06-08',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- maria
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('gisela ceballos') ORDER BY id ASC LIMIT 1),4,'2025-06-11','2025-06-13',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- gisela
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('gustavo canales') ORDER BY id ASC LIMIT 1),1,'2025-06-12','2025-06-13',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- gustavo
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('gabriela verdugo') ORDER BY id ASC LIMIT 1),4,'2025-06-15','2025-06-19',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- gabriela
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('horacio rojas') ORDER BY id ASC LIMIT 1),4,'2025-06-19','2025-06-25',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- horacio
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('hernan wunderlich') ORDER BY id ASC LIMIT 1),4,'2025-06-25','2025-06-29',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- hernan
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('ingrid mellado') ORDER BY id ASC LIMIT 1),3,'2025-06-19','2025-06-22',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- ingrid
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('oscar contreras') ORDER BY id ASC LIMIT 1),7,'2025-06-19','2025-06-22',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- oscar
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('carolina andrea peña') ORDER BY id ASC LIMIT 1),1,'2025-06-19','2025-06-21',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- carolina
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('atigilio') ORDER BY id ASC LIMIT 1),3,'2025-06-22','2025-06-27',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- Atiglio
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('margorie henriquez') ORDER BY id ASC LIMIT 1),7,'2025-06-23','2025-06-26',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- margorie
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('carlos delgado') ORDER BY id ASC LIMIT 1),1,'2025-06-21','2025-06-23',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- carlos
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('paulina vergara') ORDER BY id ASC LIMIT 1),3,'2025-06-27','2025-06-29',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- paulina
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('jose vargas') ORDER BY id ASC LIMIT 1),7,'2025-06-26','2025-06-29',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- jose
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('carolina senn') ORDER BY id ASC LIMIT 1),1,'2025-06-25','2025-06-27',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- carolina
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('paulina muñoz') ORDER BY id ASC LIMIT 1),1,'2025-06-27','2025-06-29',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- paulina
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('debora castillo') ORDER BY id ASC LIMIT 1),7,'2025-06-30','2025-07-04',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- bebora
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('romina sanhueza') ORDER BY id ASC LIMIT 1),1,'2025-06-30','2025-07-03',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- romina
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('cesar gomez') ORDER BY id ASC LIMIT 1),4,'2025-07-01','2025-07-04',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- cesar
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('geraldine saez') ORDER BY id ASC LIMIT 1),1,'2025-07-03','2025-07-05',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- geraldine
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('carolina diaz yaeger') ORDER BY id ASC LIMIT 1),3,'2025-07-03','2025-07-06',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- carolina
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('michel angelo lapadula') ORDER BY id ASC LIMIT 1),1,'2025-07-05','2025-07-11',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- michelangelo
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('alexandra garcia') ORDER BY id ASC LIMIT 1),7,'2025-07-05','2025-07-12',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- alexandra
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('vinicius cruz') ORDER BY id ASC LIMIT 1),4,'2025-07-05','2025-07-12',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- vinicius
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('greg bull') ORDER BY id ASC LIMIT 1),3,'2025-07-10','2025-07-13',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- greg
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('paulo unzueta') ORDER BY id ASC LIMIT 1),1,'2025-07-11','2025-07-14',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- paulo
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('diego coelho') ORDER BY id ASC LIMIT 1),4,'2025-07-12','2025-07-19',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- diego
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('yves romero') ORDER BY id ASC LIMIT 1),3,'2025-07-13','2025-07-16',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- Yves
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('felipe villa vicencio') ORDER BY id ASC LIMIT 1),7,'2025-07-12','2025-07-13',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- felipe
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('paola romero') ORDER BY id ASC LIMIT 1),1,'2025-07-14','2025-07-20',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- paola
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('carolina alvarez') ORDER BY id ASC LIMIT 1),1,'2025-07-21','2025-07-27',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- carolina
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('catalina riveros') ORDER BY id ASC LIMIT 1),7,'2025-07-15','2025-07-20',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- catalina
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('hernan ferrera') ORDER BY id ASC LIMIT 1),7,'2025-07-21','2025-07-25',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- hernan
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('marcio zanetti') ORDER BY id ASC LIMIT 1),4,'2025-07-21','2025-07-26',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- marcio
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('gloria noguera') ORDER BY id ASC LIMIT 1),1,'2025-07-21','2025-07-27',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- gloria
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('matias lomboy') ORDER BY id ASC LIMIT 1),3,'2025-07-23','2025-07-26',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- matias
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('pamela espinoza') ORDER BY id ASC LIMIT 1),7,'2025-07-25','2025-07-27',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- pamela
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('carlos valenzuela') ORDER BY id ASC LIMIT 1),4,'2025-07-26','2025-07-29',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- carlos
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('andres larrain') ORDER BY id ASC LIMIT 1),3,'2025-07-26','2025-07-28',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- andres
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('christian gardiol') ORDER BY id ASC LIMIT 1),3,'2025-07-29','2025-07-30',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- cristian
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('jorge erlwein') ORDER BY id ASC LIMIT 1),1,'2025-07-30','2025-08-03',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- jorge
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('felipe castaña') ORDER BY id ASC LIMIT 1),4,'2025-07-31','2025-08-04',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- felipe
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('brandyn phillips') ORDER BY id ASC LIMIT 1),7,'2025-07-31','2025-08-06',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- brandyn
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('evelyn malgarejo') ORDER BY id ASC LIMIT 1),3,'2025-07-31','2025-08-04',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- evelyn
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('maria constanza moraga') ORDER BY id ASC LIMIT 1),4,'2025-08-04','2025-08-08',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- M. Constanza
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('borja') ORDER BY id ASC LIMIT 1),1,'2025-08-03','2025-08-10',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- borja
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('andrea romeny') ORDER BY id ASC LIMIT 1),7,'2025-08-06','2025-08-10',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- andrea
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('andrea') ORDER BY id ASC LIMIT 1),3,'2025-08-06','2025-08-10',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- andrea
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('yamyl jarufe') ORDER BY id ASC LIMIT 1),4,'2025-08-08','2025-08-11',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- yamyl
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('ramiro quiroga') ORDER BY id ASC LIMIT 1),1,'2025-08-11','2025-08-14',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- ramiro
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('juan pablo') ORDER BY id ASC LIMIT 1),7,'2025-08-12','2025-08-13',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- juan pablo
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('claudia cortes') ORDER BY id ASC LIMIT 1),4,'2025-08-13','2025-08-17',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- claudia
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('ignacio mellado') ORDER BY id ASC LIMIT 1),4,'2025-08-17','2025-08-20',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- ignacio
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('javier lescano') ORDER BY id ASC LIMIT 1),7,'2025-08-13','2025-08-14',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- javier
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('begoña asfura') ORDER BY id ASC LIMIT 1),3,'2025-08-14','2025-08-17',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- begoña
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('pablo rodriguez carrasco') ORDER BY id ASC LIMIT 1),1,'2025-08-15','2025-08-18',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- pablo
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('daniela herrera') ORDER BY id ASC LIMIT 1),7,'2025-08-15','2025-08-18',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- daniela
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('diego cid') ORDER BY id ASC LIMIT 1),1,'2025-08-18','2025-08-20',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- diego
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('gerardo ramos') ORDER BY id ASC LIMIT 1),1,'2025-08-21','2025-08-24',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- gerardo
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('javier diaz') ORDER BY id ASC LIMIT 1),3,'2025-08-21','2025-08-25',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- javier
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('pamela vera') ORDER BY id ASC LIMIT 1),7,'2025-08-22','2025-08-24',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- pamela
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('victor santos') ORDER BY id ASC LIMIT 1),7,'2025-08-24','2025-08-26',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- victor
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('rene tapia') ORDER BY id ASC LIMIT 1),4,'2025-08-23','2025-08-30',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- rene
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('andres vasquez') ORDER BY id ASC LIMIT 1),1,'2025-08-24','2025-08-27',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- andres
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('agus') ORDER BY id ASC LIMIT 1),1,'2025-08-27','2025-08-29',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- agus
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('tamara zarza') ORDER BY id ASC LIMIT 1),1,'2025-08-29','2025-08-31',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- tamara
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('javier perez') ORDER BY id ASC LIMIT 1),4,'2025-08-30','2025-09-01',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- javier
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('sebastian gianfagma') ORDER BY id ASC LIMIT 1),3,'2025-08-30','2025-09-06',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- sebastian
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('gaspar aunfraric') ORDER BY id ASC LIMIT 1),1,'2025-08-31','2025-09-06',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- gaspar
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('martin basilio') ORDER BY id ASC LIMIT 1),7,'2025-08-31','2025-09-04',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- martin
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('maria victoria gozalves') ORDER BY id ASC LIMIT 1),4,'2025-09-01','2025-09-05',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- maria
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('exequeil') ORDER BY id ASC LIMIT 1),3,'2025-09-06','2025-09-07',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- ezequiel
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('thomas hoel') ORDER BY id ASC LIMIT 1),7,'2025-09-05','2025-09-07',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- thomas
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('oscar') ORDER BY id ASC LIMIT 1),7,'2025-09-07','2025-09-08',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- oscar
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('juan') ORDER BY id ASC LIMIT 1),4,'2025-09-08','2025-09-09',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- juan
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('andraz') ORDER BY id ASC LIMIT 1),1,'2025-09-09','2025-10-13',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- andraz
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('rodrigo salinas') ORDER BY id ASC LIMIT 1),7,'2025-09-11','2025-09-14',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- rodrigo
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('bibiana rubini') ORDER BY id ASC LIMIT 1),7,'2025-09-14','2025-09-18',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- bibiana
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('leonel muñoz') ORDER BY id ASC LIMIT 1),4,'2025-09-13','2025-09-17',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- leonel
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('ximena moraga') ORDER BY id ASC LIMIT 1),3,'2025-09-13','2025-09-18',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- ximena
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('jaime') ORDER BY id ASC LIMIT 1),3,'2025-09-18','2025-09-20',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- jaime
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('ignacio mellado') ORDER BY id ASC LIMIT 1),7,'2025-09-20','2025-10-01',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- ignacio
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('lourdes velasques') ORDER BY id ASC LIMIT 1),4,'2025-09-17','2025-09-22',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- lourdes
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('rene valdenegro') ORDER BY id ASC LIMIT 1),7,'2025-09-18','2025-09-20',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- rene
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('marta martu') ORDER BY id ASC LIMIT 1),3,'2025-09-20','2025-09-24',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- martu
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('bosnia refugio 1') ORDER BY id ASC LIMIT 1),3,'2025-09-26','2025-10-16',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- bosnia
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('andorra casa') ORDER BY id ASC LIMIT 1),4,'2025-09-27','2025-10-16',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- andorra
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('bosnia refugio 1') ORDER BY id ASC LIMIT 1),7,'2025-10-01','2025-10-16',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- bosnia
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('agustin') ORDER BY id ASC LIMIT 1),4,'2025-10-16','2025-10-21',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- agustin
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('valentina riquelme') ORDER BY id ASC LIMIT 1),4,'2025-10-28','2025-11-01',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- valentina
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('manuel') ORDER BY id ASC LIMIT 1),1,'2025-11-28','2025-11-30',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- manuel
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('valentina riquelme') ORDER BY id ASC LIMIT 1),4,'2025-12-01','2025-12-02',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- valentina
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('tomas correa') ORDER BY id ASC LIMIT 1),7,'2025-12-17','2025-12-19',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- tomas
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('camila muñoz') ORDER BY id ASC LIMIT 1),4,'2025-12-27','2025-12-31',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'), -- camila
  ((SELECT id FROM guests WHERE LOWER(full_name)=LOWER('victor santos') ORDER BY id ASC LIMIT 1),1,'2025-12-27','2025-12-30',0,0,'direct','transfer','confirmed','confirmed','ASSET_CORRECTED_2025_2026'); -- victor

